//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cookie {
            get {
                return ((string)(this["cookie"]));
            }
            set {
                this["cookie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string links {
            get {
                return ((string)(this["links"]));
            }
            set {
                this["links"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string instances {
            get {
                return ((string)(this["instances"]));
            }
            set {
                this["instances"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string projects {
            get {
                return ((string)(this["projects"]));
            }
            set {
                this["projects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool update {
            get {
                return ((bool)(this["update"]));
            }
            set {
                this["update"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autorefresh {
            get {
                return ((bool)(this["autorefresh"]));
            }
            set {
                this["autorefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string projOrgExcl {
            get {
                return ((string)(this["projOrgExcl"]));
            }
            set {
                this["projOrgExcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cachingEnabled {
            get {
                return ((bool)(this["cachingEnabled"]));
            }
            set {
                this["cachingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cachingStore {
            get {
                return ((string)(this["cachingStore"]));
            }
            set {
                this["cachingStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minimizeToNotificationArea {
            get {
                return ((bool)(this["minimizeToNotificationArea"]));
            }
            set {
                this["minimizeToNotificationArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool keepCache {
            get {
                return ((bool)(this["keepCache"]));
            }
            set {
                this["keepCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alwaysLogAsAdmin {
            get {
                return ((bool)(this["alwaysLogAsAdmin"]));
            }
            set {
                this["alwaysLogAsAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool uriSchemeEnabled {
            get {
                return ((bool)(this["uriSchemeEnabled"]));
            }
            set {
                this["uriSchemeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RDPCredentialsEnabled {
            get {
                return ((bool)(this["RDPCredentialsEnabled"]));
            }
            set {
                this["RDPCredentialsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalCredentialsEnabled {
            get {
                return ((bool)(this["LocalCredentialsEnabled"]));
            }
            set {
                this["LocalCredentialsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lcs.dynamics.com")]
        public string lcsURL {
            get {
                return ((string)(this["lcsURL"]));
            }
            set {
                this["lcsURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://diag.lcs.dynamics.com")]
        public string lcsDiagURL {
            get {
                return ((string)(this["lcsDiagURL"]));
            }
            set {
                this["lcsDiagURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://update.lcs.dynamics.com")]
        public string lcsUpdateURL {
            get {
                return ((string)(this["lcsUpdateURL"]));
            }
            set {
                this["lcsUpdateURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://fix.lcs.dynamics.com")]
        public string lcsFixURL {
            get {
                return ((string)(this["lcsFixURL"]));
            }
            set {
                this["lcsFixURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""United States"": {
    ""Type"": 0,
    ""Name"": ""United States"",
    ""LcsUrl"": ""https://lcs.dynamics.com"",
    ""LcsDiagUrl"": ""https://diag.lcs.dynamics.com"",
    ""LcsUpdateUrl"": ""https://update.lcs.dynamics.com"",
    ""LcsFixUrl"": ""https://fix.lcs.dynamics.com""
  },
  ""Europe"": {
    ""Type"": 1,
    ""Name"": ""Europe"",
    ""LcsUrl"": ""https://eu.lcs.dynamics.com"",
    ""LcsDiagUrl"": ""https://eu.diag.lcs.dynamics.com"",
    ""LcsUpdateUrl"": ""https://eu.update.lcs.dynamics.com"",
    ""LcsFixUrl"": ""https://eu.fix.lcs.dynamics.com""
  },
  ""France"": {
    ""Type"": 1,
    ""Name"": ""France"",
    ""LcsUrl"": ""https://fr.lcs.dynamics.com"",
    ""LcsDiagUrl"": ""https://fr.diag.lcs.dynamics.com"",
    ""LcsUpdateUrl"": ""https://fr.update.lcs.dynamics.com"",
    ""LcsFixUrl"": ""https://fr.fix.lcs.dynamics.com""
  },
  ""South Africa"": {
    ""Type"": 1,
    ""Name"": ""South Africa"",
    ""LcsUrl"": ""https://sa.lcs.dynamics.com"",
    ""LcsDiagUrl"": ""https://sa.diag.lcs.dynamics.com"",
    ""LcsUpdateUrl"": ""https://sa.update.lcs.dynamics.com"",
    ""LcsFixUrl"": ""https://sa.fix.lcs.dynamics.com""
  }
}")]
        public string lcsGeos {
            get {
                return ((string)(this["lcsGeos"]));
            }
            set {
                this["lcsGeos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string currentLcsGeo {
            get {
                return ((string)(this["currentLcsGeo"]));
            }
            set {
                this["currentLcsGeo"] = value;
            }
        }
    }
}
